### ISSUE TITLE
test looping

### ISSUE THREAD

**Issue by lb1601com** [lb1601com/GitReminder-Tester#14]
@gh-lb1601com 2d @gh-lb1601com

**Comment by lb1601com** [comment]
@gh-lb1601com 0d @lb1601com

**Comment by lb1601com** [comment]
@gh-lb1601com 3d @blabla

**Comment by lb1601com** [comment]
@gh-lb1601com 0d @blabla

**Comment by gh-lb1601com** [comment]
Can't assign this user, cause I did not find it this repo :(
